title: Jun-Wei Lin
description: 

url: jwlin.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: jwlin
   twitter: 
   facebook: 
   email: user@user.com

google_analytics: ""
