### Site info:
title: castman
tagline: Through readiness and discipline we are masters of our fate.
author: Jun-Wei Lin
email: ""
description: "Castman's blog." # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jwlin.github.io" # the base hostname & protocol for your site
locale: zh_TW

### Personal info and site tools info:
twitter_username: ""
github_username: "jwlin"
disqus_shortname: ""
favicon: ""
aboutme: # these are shown on aboutme-sidebar.
aboutme_photo: https://avatars2.githubusercontent.com/u/5249835?v=3&s=460 # your photo.


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown when ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "


### Build settings
markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
